//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanji_Jishyo.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kanji
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kanji()
        {
            this.Examples = new HashSet<Examples>();
            this.KanjiReadings = new HashSet<KanjiReadings>();
        }
    
        public int KanjiId { get; set; }
        public string KanjiMean { get; set; }
        public int KanjiStrokes { get; set; }
        public string KanjiImage { get; set; }
        public byte[] KanjiDraw { get; set; }
        public string KanjiKey { get; set; }
        public Nullable<int> KanjiRatingId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examples> Examples { get; set; }
        public virtual KanjiRating KanjiRating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KanjiReadings> KanjiReadings { get; set; }
        public virtual Words Words { get; set; }
    }
}
