//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanji_Jishyo.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class KanjiReadings
    {
        public int Id { get; set; }
        public int KanjiId { get; set; }
        public string OnYomi1 { get; set; }
        public string OnYomi2 { get; set; }
        public string KunYomi1 { get; set; }
        public string KunYomi2 { get; set; }
        public string KunYomi3 { get; set; }
    
        public virtual Kanji Kanji { get; set; }
    }
}
