//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanji_Jishyo.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class KanjiRating
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KanjiRating()
        {
            this.Kanji = new HashSet<Kanji>();
        }
    
        public int KanjiRatingId { get; set; }
        public double PopularityRating { get; set; }
        public double JLPTRating { get; set; }
        public double SchoolRating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kanji> Kanji { get; set; }
    }
}
